name: Frontend code quality check

on:
  push:
    branches: [main, "*dev"]
  pull_request:
    branches: [main, "*dev"]
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Prepare train folder
        working-directory: frontend/service
        run: |
          mkdir -p train
          echo '[]' > train/infer.json
          echo '{}' > train/contrib.json
          echo '??' > train/model.onnx

      - name: Setup uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Cache postinstall artifacts
        uses: actions/cache@v5
        with:
          path: frontend/ui/.cache
          key: ${{ runner.os }}-frontend-postinstall-cache

      - name: Setup Vite+ and install dependencies
        uses: voidzero-dev/setup-vp@v1.21.1
        with:
          node-version: latest
          cache: true

      - name: Vite+ check
        run: vp check

      - name: Svelte type check
        run: vp run detypify-ui#check
